### PR TITLE
Add optional datetime

### PR DESCRIPTION
**Pull request by henriquepedrosa**
See #1107
### Added
- optional parameter to get data with datetime

### CODE REVIEW

**Comment by henriquepedrosa** [comment]
@andreascreten @dimsav review please

**Comment by henriquepedrosa** [comment]
@andreascreten should I update to allow to do the "range of dates" request?

**Comment by dimsav** [comment]
Looks good.

**Comment by andreascreten** [comment]
> @andreascreten should I update to allow to do the "range of dates" request?

Nah.

**Pull request merged**
